disabled_rules:
  - trailing_whitespace
  - line_length
  - function_parameter_count
excluded:
  - Pods

# Customized rules
identifier_name:
  excluded:
    - id
type_name:
  excluded:
    - UI
function_body_length:
  warning: 80
large_tuple:
  warning: 5
